"""Database seeder populating global cloud regions with realistic telemetry and coordinates."""

from decimal import Decimal
import logging
import uuid
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.persistence.models.region import Region

logger = logging.getLogger(__name__)

DEFAULT_REGIONS = [
    # North America
    {
        "code": "us-east-1",
        "name": "US East (N. Virginia)",
        "electricity_maps_zone": "US-MIDA-PJM",
        "provider": "AWS",
        "country": "USA",
        "latitude": Decimal("38.130000"),
        "longitude": Decimal("-78.450000"),
        "max_cpu_capacity": Decimal("2048.00"),
        "max_memory_capacity": Decimal("8192.00"),
        "current_utilization": Decimal("0.3800"),
        "performance_factor": Decimal("1.1000"),
        "idle_power_watts": Decimal("130.00"),
        "peak_power_watts": Decimal("550.00"),
        "network_latency_ms": Decimal("30.00"),
        "is_available": True,
        "is_active": True,
    },
    {
        "code": "us-east-2",
        "name": "US East (Ohio)",
        "electricity_maps_zone": "US-MIDW-MISO",
        "provider": "AWS",
        "country": "USA",
        "latitude": Decimal("40.367500"),
        "longitude": Decimal("-82.996200"),
        "max_cpu_capacity": Decimal("1024.00"),
        "max_memory_capacity": Decimal("4096.00"),
        "current_utilization": Decimal("0.2800"),
        "performance_factor": Decimal("1.0500"),
        "idle_power_watts": Decimal("120.00"),
        "peak_power_watts": Decimal("500.00"),
        "network_latency_ms": Decimal("35.00"),
        "is_available": True,
        "is_active": True,
    },
    {
        "code": "us-west-1",
        "name": "US West (N. California)",
        "electricity_maps_zone": "US-CAL-CISO",
        "provider": "AWS",
        "country": "USA",
        "latitude": Decimal("37.774900"),
        "longitude": Decimal("-122.419400"),
        "max_cpu_capacity": Decimal("1024.00"),
        "max_memory_capacity": Decimal("4096.00"),
        "current_utilization": Decimal("0.3200"),
        "performance_factor": Decimal("1.1000"),
        "idle_power_watts": Decimal("125.00"),
        "peak_power_watts": Decimal("520.00"),
        "network_latency_ms": Decimal("40.00"),
        "is_available": True,
        "is_active": True,
    },
    {
        "code": "us-west-2",
        "name": "US West (Oregon)",
        "electricity_maps_zone": "US-NW-PACW",
        "provider": "AWS",
        "country": "USA",
        "latitude": Decimal("45.523100"),
        "longitude": Decimal("-122.676500"),
        "max_cpu_capacity": Decimal("2048.00"),
        "max_memory_capacity": Decimal("8192.00"),
        "current_utilization": Decimal("0.3500"),
        "performance_factor": Decimal("1.1500"),
        "idle_power_watts": Decimal("130.00"),
        "peak_power_watts": Decimal("550.00"),
        "network_latency_ms": Decimal("38.00"),
        "is_available": True,
        "is_active": True,
    },
    {
        "code": "ca-central-1",
        "name": "Canada (Central)",
        "electricity_maps_zone": "CA-QC",
        "provider": "AWS",
        "country": "Canada",
        "latitude": Decimal("45.501700"),
        "longitude": Decimal("-73.567300"),
        "max_cpu_capacity": Decimal("1024.00"),
        "max_memory_capacity": Decimal("4096.00"),
        "current_utilization": Decimal("0.2400"),
        "performance_factor": Decimal("1.1000"),
        "idle_power_watts": Decimal("115.00"),
        "peak_power_watts": Decimal("480.00"),
        "network_latency_ms": Decimal("32.00"),
        "is_available": True,
        "is_active": True,
    },
    {
        "code": "ca-west-1",
        "name": "Canada (Calgary)",
        "electricity_maps_zone": "CA-AB",
        "provider": "AWS",
        "country": "Canada",
        "latitude": Decimal("51.044700"),
        "longitude": Decimal("-114.071900"),
        "max_cpu_capacity": Decimal("512.00"),
        "max_memory_capacity": Decimal("2048.00"),
        "current_utilization": Decimal("0.2000"),
        "performance_factor": Decimal("1.0500"),
        "idle_power_watts": Decimal("110.00"),
        "peak_power_watts": Decimal("460.00"),
        "network_latency_ms": Decimal("45.00"),
        "is_available": True,
        "is_active": True,
    },

    # South America
    {
        "code": "sa-east-1",
        "name": "South America (São Paulo)",
        "electricity_maps_zone": "BR-CS",
        "provider": "AWS",
        "country": "Brazil",
        "latitude": Decimal("-23.550500"),
        "longitude": Decimal("-46.633300"),
        "max_cpu_capacity": Decimal("1024.00"),
        "max_memory_capacity": Decimal("4096.00"),
        "current_utilization": Decimal("0.3000"),
        "performance_factor": Decimal("1.0000"),
        "idle_power_watts": Decimal("125.00"),
        "peak_power_watts": Decimal("500.00"),
        "network_latency_ms": Decimal("65.00"),
        "is_available": True,
        "is_active": True,
    },

    # Europe
    {
        "code": "eu-north-1",
        "name": "Europe (Stockholm)",
        "electricity_maps_zone": "SE-SE3",
        "provider": "AWS",
        "country": "Sweden",
        "latitude": Decimal("59.329300"),
        "longitude": Decimal("18.068600"),
        "max_cpu_capacity": Decimal("1024.00"),
        "max_memory_capacity": Decimal("4096.00"),
        "current_utilization": Decimal("0.2200"),
        "performance_factor": Decimal("1.2000"),
        "idle_power_watts": Decimal("120.00"),
        "peak_power_watts": Decimal("400.00"),
        "network_latency_ms": Decimal("25.00"),
        "is_available": True,
        "is_active": True,
    },
    {
        "code": "eu-west-1",
        "name": "Europe (Ireland)",
        "electricity_maps_zone": "IE",
        "provider": "AWS",
        "country": "Ireland",
        "latitude": Decimal("53.349800"),
        "longitude": Decimal("-6.260300"),
        "max_cpu_capacity": Decimal("1536.00"),
        "max_memory_capacity": Decimal("6144.00"),
        "current_utilization": Decimal("0.3400"),
        "performance_factor": Decimal("1.1500"),
        "idle_power_watts": Decimal("125.00"),
        "peak_power_watts": Decimal("520.00"),
        "network_latency_ms": Decimal("18.00"),
        "is_available": True,
        "is_active": True,
    },
    {
        "code": "eu-west-2",
        "name": "Europe (London)",
        "electricity_maps_zone": "GB",
        "provider": "AWS",
        "country": "United Kingdom",
        "latitude": Decimal("51.507400"),
        "longitude": Decimal("-0.127800"),
        "max_cpu_capacity": Decimal("1024.00"),
        "max_memory_capacity": Decimal("4096.00"),
        "current_utilization": Decimal("0.2600"),
        "performance_factor": Decimal("1.1000"),
        "idle_power_watts": Decimal("115.00"),
        "peak_power_watts": Decimal("460.00"),
        "network_latency_ms": Decimal("20.00"),
        "is_available": True,
        "is_active": True,
    },
    {
        "code": "eu-west-3",
        "name": "Europe (Paris)",
        "electricity_maps_zone": "FR",
        "provider": "AWS",
        "country": "France",
        "latitude": Decimal("48.856600"),
        "longitude": Decimal("2.352200"),
        "max_cpu_capacity": Decimal("1024.00"),
        "max_memory_capacity": Decimal("4096.00"),
        "current_utilization": Decimal("0.2800"),
        "performance_factor": Decimal("1.1000"),
        "idle_power_watts": Decimal("100.00"),
        "peak_power_watts": Decimal("450.00"),
        "network_latency_ms": Decimal("15.00"),
        "is_available": True,
        "is_active": True,
    },
    {
        "code": "eu-central-1",
        "name": "Europe (Frankfurt)",
        "electricity_maps_zone": "DE",
        "provider": "AWS",
        "country": "Germany",
        "latitude": Decimal("50.110900"),
        "longitude": Decimal("8.682100"),
        "max_cpu_capacity": Decimal("2048.00"),
        "max_memory_capacity": Decimal("8192.00"),
        "current_utilization": Decimal("0.3500"),
        "performance_factor": Decimal("1.3000"),
        "idle_power_watts": Decimal("150.00"),
        "peak_power_watts": Decimal("600.00"),
        "network_latency_ms": Decimal("10.00"),
        "is_available": True,
        "is_active": True,
    },
    {
        "code": "eu-central-2",
        "name": "Europe (Zurich)",
        "electricity_maps_zone": "CH",
        "provider": "AWS",
        "country": "Switzerland",
        "latitude": Decimal("47.376900"),
        "longitude": Decimal("8.541700"),
        "max_cpu_capacity": Decimal("512.00"),
        "max_memory_capacity": Decimal("2048.00"),
        "current_utilization": Decimal("0.1900"),
        "performance_factor": Decimal("1.1500"),
        "idle_power_watts": Decimal("105.00"),
        "peak_power_watts": Decimal("440.00"),
        "network_latency_ms": Decimal("12.00"),
        "is_available": True,
        "is_active": True,
    },
    {
        "code": "eu-south-1",
        "name": "Europe (Milan)",
        "electricity_maps_zone": "IT-NO",
        "provider": "AWS",
        "country": "Italy",
        "latitude": Decimal("45.464200"),
        "longitude": Decimal("9.190000"),
        "max_cpu_capacity": Decimal("512.00"),
        "max_memory_capacity": Decimal("2048.00"),
        "current_utilization": Decimal("0.2500"),
        "performance_factor": Decimal("1.0500"),
        "idle_power_watts": Decimal("110.00"),
        "peak_power_watts": Decimal("470.00"),
        "network_latency_ms": Decimal("16.00"),
        "is_available": True,
        "is_active": True,
    },
    {
        "code": "eu-south-2",
        "name": "Europe (Spain)",
        "electricity_maps_zone": "ES",
        "provider": "AWS",
        "country": "Spain",
        "latitude": Decimal("40.416800"),
        "longitude": Decimal("-3.703800"),
        "max_cpu_capacity": Decimal("512.00"),
        "max_memory_capacity": Decimal("2048.00"),
        "current_utilization": Decimal("0.2200"),
        "performance_factor": Decimal("1.1000"),
        "idle_power_watts": Decimal("110.00"),
        "peak_power_watts": Decimal("460.00"),
        "network_latency_ms": Decimal("22.00"),
        "is_available": True,
        "is_active": True,
    },

    # Africa & Middle East
    {
        "code": "af-south-1",
        "name": "Africa (Cape Town)",
        "electricity_maps_zone": "ZA",
        "provider": "AWS",
        "country": "South Africa",
        "latitude": Decimal("-33.924900"),
        "longitude": Decimal("18.424100"),
        "max_cpu_capacity": Decimal("512.00"),
        "max_memory_capacity": Decimal("2048.00"),
        "current_utilization": Decimal("0.2000"),
        "performance_factor": Decimal("1.0000"),
        "idle_power_watts": Decimal("115.00"),
        "peak_power_watts": Decimal("480.00"),
        "network_latency_ms": Decimal("75.00"),
        "is_available": True,
        "is_active": True,
    },
    {
        "code": "me-central-1",
        "name": "Middle East (UAE)",
        "electricity_maps_zone": "AE",
        "provider": "AWS",
        "country": "United Arab Emirates",
        "latitude": Decimal("25.204800"),
        "longitude": Decimal("55.270800"),
        "max_cpu_capacity": Decimal("512.00"),
        "max_memory_capacity": Decimal("2048.00"),
        "current_utilization": Decimal("0.2200"),
        "performance_factor": Decimal("1.1000"),
        "idle_power_watts": Decimal("120.00"),
        "peak_power_watts": Decimal("490.00"),
        "network_latency_ms": Decimal("45.00"),
        "is_available": True,
        "is_active": True,
    },

    # Asia Pacific & India
    {
        "code": "ap-northeast-1",
        "name": "Asia Pacific (Tokyo)",
        "electricity_maps_zone": "JP-TK",
        "provider": "AWS",
        "country": "Japan",
        "latitude": Decimal("35.676200"),
        "longitude": Decimal("139.650300"),
        "max_cpu_capacity": Decimal("1536.00"),
        "max_memory_capacity": Decimal("6144.00"),
        "current_utilization": Decimal("0.3100"),
        "performance_factor": Decimal("1.1500"),
        "idle_power_watts": Decimal("110.00"),
        "peak_power_watts": Decimal("480.00"),
        "network_latency_ms": Decimal("50.00"),
        "is_available": True,
        "is_active": True,
    },
    {
        "code": "ap-northeast-2",
        "name": "Asia Pacific (Seoul)",
        "electricity_maps_zone": "KR",
        "provider": "AWS",
        "country": "South Korea",
        "latitude": Decimal("37.566500"),
        "longitude": Decimal("126.978000"),
        "max_cpu_capacity": Decimal("1024.00"),
        "max_memory_capacity": Decimal("4096.00"),
        "current_utilization": Decimal("0.2700"),
        "performance_factor": Decimal("1.1000"),
        "idle_power_watts": Decimal("115.00"),
        "peak_power_watts": Decimal("490.00"),
        "network_latency_ms": Decimal("52.00"),
        "is_available": True,
        "is_active": True,
    },
    {
        "code": "ap-northeast-3",
        "name": "Asia Pacific (Osaka)",
        "electricity_maps_zone": "JP-KN",
        "provider": "AWS",
        "country": "Japan",
        "latitude": Decimal("34.693700"),
        "longitude": Decimal("135.502300"),
        "max_cpu_capacity": Decimal("512.00"),
        "max_memory_capacity": Decimal("2048.00"),
        "current_utilization": Decimal("0.2100"),
        "performance_factor": Decimal("1.1000"),
        "idle_power_watts": Decimal("105.00"),
        "peak_power_watts": Decimal("450.00"),
        "network_latency_ms": Decimal("54.00"),
        "is_available": True,
        "is_active": True,
    },
    {
        "code": "ap-southeast-1",
        "name": "Asia Pacific (Singapore)",
        "electricity_maps_zone": "SG",
        "provider": "AWS",
        "country": "Singapore",
        "latitude": Decimal("1.352100"),
        "longitude": Decimal("103.819800"),
        "max_cpu_capacity": Decimal("1024.00"),
        "max_memory_capacity": Decimal("4096.00"),
        "current_utilization": Decimal("0.3300"),
        "performance_factor": Decimal("1.1500"),
        "idle_power_watts": Decimal("120.00"),
        "peak_power_watts": Decimal("510.00"),
        "network_latency_ms": Decimal("42.00"),
        "is_available": True,
        "is_active": True,
    },
    {
        "code": "ap-southeast-2",
        "name": "Asia Pacific (Sydney)",
        "electricity_maps_zone": "AUS-NSW",
        "provider": "AWS",
        "country": "Australia",
        "latitude": Decimal("-33.868800"),
        "longitude": Decimal("151.209300"),
        "max_cpu_capacity": Decimal("1024.00"),
        "max_memory_capacity": Decimal("4096.00"),
        "current_utilization": Decimal("0.2900"),
        "performance_factor": Decimal("1.1000"),
        "idle_power_watts": Decimal("120.00"),
        "peak_power_watts": Decimal("500.00"),
        "network_latency_ms": Decimal("58.00"),
        "is_available": True,
        "is_active": True,
    },
    {
        "code": "ap-southeast-4",
        "name": "Asia Pacific (Melbourne)",
        "electricity_maps_zone": "AUS-VIC",
        "provider": "AWS",
        "country": "Australia",
        "latitude": Decimal("-37.813600"),
        "longitude": Decimal("144.963100"),
        "max_cpu_capacity": Decimal("512.00"),
        "max_memory_capacity": Decimal("2048.00"),
        "current_utilization": Decimal("0.2200"),
        "performance_factor": Decimal("1.0500"),
        "idle_power_watts": Decimal("110.00"),
        "peak_power_watts": Decimal("470.00"),
        "network_latency_ms": Decimal("60.00"),
        "is_available": True,
        "is_active": True,
    },
    {
        "code": "ap-south-1",
        "name": "Asia Pacific (Mumbai)",
        "electricity_maps_zone": "IN-WE",
        "provider": "AWS",
        "country": "India",
        "latitude": Decimal("19.076000"),
        "longitude": Decimal("72.877700"),
        "max_cpu_capacity": Decimal("1024.00"),
        "max_memory_capacity": Decimal("4096.00"),
        "current_utilization": Decimal("0.3600"),
        "performance_factor": Decimal("1.1500"),
        "idle_power_watts": Decimal("130.00"),
        "peak_power_watts": Decimal("540.00"),
        "network_latency_ms": Decimal("48.00"),
        "is_available": True,
        "is_active": True,
    },
    {
        "code": "ap-south-2",
        "name": "Asia Pacific (Hyderabad)",
        "electricity_maps_zone": "IN-SO",
        "provider": "AWS",
        "country": "India",
        "latitude": Decimal("17.385000"),
        "longitude": Decimal("78.486700"),
        "max_cpu_capacity": Decimal("512.00"),
        "max_memory_capacity": Decimal("2048.00"),
        "current_utilization": Decimal("0.2300"),
        "performance_factor": Decimal("1.0500"),
        "idle_power_watts": Decimal("115.00"),
        "peak_power_watts": Decimal("480.00"),
        "network_latency_ms": Decimal("50.00"),
        "is_available": True,
        "is_active": True,
    },
]

# Legacy alias mappings to canonical provider regions
LEGACY_CODE_MAP = {
    "se-sto": "eu-north-1",
    "fr-par": "eu-west-3",
    "de-fra": "eu-central-1",
    "us-east": "us-east-1",
    "uk-lon": "eu-west-2",
    "jp-tyo": "ap-northeast-1",
    "pl-war": "eu-central-1",
}


async def seed_default_regions(session: AsyncSession) -> int:
    """Seeds or updates canonical AWS compute regions ensuring explicit Electricity Maps zones.

    Preserves foreign key integrity by safely aliasing/migrating legacy codes if present.
    """
    result = await session.execute(select(Region))
    existing_regions = {r.code: r for r in result.scalars().all()}

    count = 0

    # 1. Update or create canonical 25 regions
    for reg_data in DEFAULT_REGIONS:
        code = reg_data["code"]
        if code in existing_regions:
            existing = existing_regions[code]
            updated = False
            for k, v in reg_data.items():
                if getattr(existing, k, None) != v:
                    setattr(existing, k, v)
                    updated = True
            if updated:
                count += 1
        else:
            region = Region(
                id=uuid.uuid4(),
                **reg_data,
            )
            session.add(region)
            count += 1

    # 2. Deactivate any legacy non-canonical region codes if they exist, preserving FK references
    for legacy_code in LEGACY_CODE_MAP:
        if legacy_code in existing_regions and legacy_code not in [r["code"] for r in DEFAULT_REGIONS]:
            existing = existing_regions[legacy_code]
            if existing.is_active or existing.is_available:
                existing.is_active = False
                existing.is_available = False
                count += 1

    if count > 0:
        await session.commit()
        logger.info(f"Successfully seeded/updated {count} canonical cloud regions.")
    else:
        logger.debug("Cloud regions already up to date in PostgreSQL.")
    return count
